env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0
  no-trailing-spaces:
    - error
    - skipBlankLines: true
      ignoreComments: true
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-prototype-builtins:
    - warn
